name: Build and Deploy AI (FastAPI & LangChain) to Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # 모든 명령어가 model2 디렉토리 내에서 실행되도록 설정
    defaults:
      run:
        working-directory: model2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # (선택 사항) 테스트가 있다면 실행, 없으면 생략
      - name: Run Tests
        run: |
          echo "No tests configured"  # 또는 실제 테스트 명령어 실행

      - name: Build Docker Image
        run: |
          docker build -t asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ktb-ai/my-ai:v1 .

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Google Cloud
        run: |
          gcloud auth configure-docker asia-northeast3-docker.pkg.dev --quiet

      - name: Push Docker Image
        run: |
          docker push asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ktb-ai/my-ai:v1

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-ai \
            --image asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ktb-ai/my-ai:v1 \
            --region asia-northeast3 \
            --platform managed \
            --allow-unauthenticated \
            --port 8080
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
