name: Build and Deploy AI to Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ai/package-lock.json

      - name: List AI directory
        run: ls -al ./ai

      - name: Install Dependencies
        working-directory: ./ai
        run: npm ci

      - name: Build Project
        working-directory: ./ai
        run: npm run build

      - name: Build Docker Image
        working-directory: ./ai
        run: |
          docker build -t asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ktb-ai/my-ai:v1 .

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev --quiet

      - name: Push Docker Image
        run: |
          docker push asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ktb-ai/my-ai:v1

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-ai \
            --image asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ktb-ai/my-ai:v1 \
            --region asia-northeast3 \
            --platform managed \
            --allow-unauthenticated \
            --port 80
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
